import { reactive, ref } from "@nuxtjs/composition-api";

export default function dataCurrency() {
  const currency = reactive<any>([
    { text: "Emirati Dirham", value: "AED" },
    { text: "Afghan Afghani", value: "AFN" },
    { text: "Albanian Lek", value: "ALL" },
    { text: "Armenian Dram", value: "AMD" },
    { text: "Dutch Guilder", value: "ANG" },
    { text: "Angolan Kwanza", value: "AOA" },
    { text: "Argentine Peso", value: "ARS" },
    { text: "Australian Dollar", value: "AUD" },
    { text: "Aruban or Dutch Guilder", value: "AWG" },
    { text: "Azerbaijan Manat", value: "AZN" },
    { text: "Bosnian Convertible Mark", value: "BAM" },
    { text: "Barbadian or Bajan Dollar", value: "BBD" },
    { text: "Bangladeshi Taka", value: "BDT" },
    { text: "Bulgarian Lev", value: "BGN" },
    { text: "Bahraini Dinar", value: "BHD" },
    { text: "Burundian Franc", value: "BIF" },
    { text: "Bermudian Dollar", value: "BMD" },
    { text: "Bruneian Dollar", value: "BND" },
    { text: "Bolivian Bolíviano", value: "BOB" },
    { text: "Brazilian Real", value: "BRL" },
    { text: "Bahamian Dollar", value: "BSD" },
    { text: "Bhutanese Ngultrum", value: "BTN" },
    { text: "Botswana Pula", value: "BWP" },
    { text: "Belarusian Ruble", value: "BYN" },
    { text: "Belizean Dollar", value: "BZD" },
    { text: "Canadian Dollar", value: "CAD" },
    { text: "Congolese Franc", value: "CDF" },
    { text: "Swiss Franc", value: "CHF" },
    { text: "Chilean Peso", value: "CLP" },
    { text: "Chinese Yuan Renminbi", value: "CNY" },
    { text: "Colombian Peso", value: "COP" },
    { text: "Costa Rican Colon", value: "CRC" },
    { text: "Cuban Convertible Peso", value: "CUC" },
    { text: "Cuban Peso", value: "CUP" },
    { text: "Cape Verdean Escudo", value: "CVE" },
    { text: "Czech Koruna", value: "CZK" },
    { text: "Djiboutian Franc", value: "DJF" },
    { text: "Danish Krone", value: "DKK" },
    { text: "Dominican Peso", value: "DOP" },
    { text: "Algerian Dinar", value: "DZD" },
    { text: "Estonian Kroon", value: "EEK" },
    { text: "Egyptian Pound", value: "EGP" },
    { text: "Eritrean Nakfa", value: "ERN" },
    { text: "Ethiopian Birr", value: "ETB" },
    { text: "Euro", value: "EUR" },
    { text: "Fijian Dollar", value: "FJD" },
    { text: "Falkland Island Pound", value: "FKP" },
    { text: "British Pound", value: "GBP" },
    { text: "Georgian Lari", value: "GEL" },
    { text: "Guernsey Pound", value: "GGP" },
    { text: "Ghanaian Cedi", value: "GHS" },
    { text: "Gibraltar Pound", value: "GIP" },
    { text: "Gambian Dalasi", value: "GMD" },
    { text: "Guinean Franc", value: "GNF" },
    { text: "Guatemalan Quetzal", value: "GTQ" },
    { text: "Guyanese Dollar", value: "GYD" },
    { text: "Hong Kong Dollar", value: "HKD" },
    { text: "Honduran Lempira", value: "HNL" },
    { text: "Croatian Kuna", value: "HRK" },
    { text: "Haitian Gourde", value: "HTG" },
    { text: "Hungarian Forint", value: "HUF" },
    { text: "Indonesian Rupiah", value: "IDR" },
    { text: "Israeli Shekel", value: "ILS" },
    { text: "Isle of Man Pound", value: "IMP" },
    { text: "Indian Rupee", value: "INR" },
    { text: "Iraqi Dinar", value: "IQD" },
    { text: "Iranian Rial", value: "IRR" },
    { text: "Icelandic Krona", value: "ISK" },
    { text: "Jersey Pound", value: "JEP" },
    { text: "Jamaican Dollar", value: "JMD" },
    { text: "Jordanian Dinar", value: "JOD" },
    { text: "Japanese Yen", value: "JPY" },
    { text: "Kenyan Shilling", value: "KES" },
    { text: "Kyrgyzstani Som", value: "KGS" },
    { text: "Cambodian Riel", value: "KHR" },
    { text: "Comorian Franc", value: "KMF" },
    { text: "North Korean Won", value: "KPW" },
    { text: "South Korean Won", value: "KRW" },
    { text: "Kuwaiti Dinar", value: "KWD" },
    { text: "Caymanian Dollar", value: "KYD" },
    { text: "Kazakhstani Tenge", value: "KZT" },
    { text: "Lao Kip", value: "LAK" },
    { text: "Lebanese Pound", value: "LBP" },
    { text: "Sri Lankan Rupee", value: "LKR" },
    { text: "Liberian Dollar", value: "LRD" },
    { text: "Basotho Loti", value: "LSL" },
    { text: "Lithuanian Litas", value: "LTL" },
    { text: "Latvian Lat", value: "LVL" },
    { text: "Libyan Dinar", value: "LYD" },
    { text: "Moroccan Dirham", value: "MAD" },
    { text: "Moldovan Leu", value: "MDL" },
    { text: "Malagasy Ariary", value: "MGA" },
    { text: "Macedonian Denar", value: "MKD" },
    { text: "Burmese Kyat", value: "MMK" },
    { text: "Mongolian Tughrik", value: "MNT" },
    { text: "Macau Pataca", value: "MOP" },
    { text: "Mauritanian Ouguiya", value: "MRU" },
    { text: "Mauritian Rupee", value: "MUR" },
    { text: "Maldivian Rufiyaa", value: "MVR" },
    { text: "Malawian Kwacha", value: "MWK" },
    { text: "Mexican Peso", value: "MXN" },
    { text: "Malaysian Ringgit", value: "MYR" },
    { text: "Mozambican Metical", value: "MZN" },
    { text: "Namibian Dollar", value: "NAD" },
    { text: "Nigerian Naira", value: "NGN" },
    { text: "Nicaraguan Cordoba", value: "NIO" },
    { text: "Norwegian Krone", value: "NOK" },
    { text: "Nepalese Rupee", value: "NPR" },
    { text: "New Zealand Dollar", value: "NZD" },
    { text: "Omani Rial", value: "OMR" },
    { text: "Panamanian Balboa", value: "PAB" },
    { text: "Peruvian Sol", value: "PEN" },
    { text: "Papua New Guinean Kina", value: "PGK" },
    { text: "Philippine Peso", value: "PHP" },
    { text: "Pakistani Rupee", value: "PKR" },
    { text: "Polish Zloty", value: "PLN" },
    { text: "Paraguayan Guarani", value: "PYG" },
    { text: "Qatari Riyal", value: "QAR" },
    { text: "Romanian Leu", value: "RON" },
    { text: "Serbian Dinar", value: "RSD" },
    { text: "Russian Ruble", value: "RUB" },
    { text: "Rwandan Franc", value: "RWF" },
    { text: "Saudi Arabian Riyal", value: "SAR" },
    { text: "Solomon Islander Dollar", value: "SBD" },
    { text: "Seychellois Rupee", value: "SCR" },
    { text: "Sudanese Pound", value: "SDG" },
    { text: "Swedish Krona", value: "SEK" },
    { text: "Singapore Dollar", value: "SGD" },
    { text: "Saint Helenian Pound", value: "SHP" },
    { text: "Sierra Leonean Leone", value: "SLL" },
    { text: "Somali Shilling", value: "SOS" },
    { text: "Seborgan Luigino", value: "SPL" },
    { text: "Surinamese Dollar", value: "SRD" },
    { text: "Sao Tomean Dobra", value: "STN" },
    { text: "Salvadoran Colon", value: "SVC" },
    { text: "Syrian Pound", value: "SYP" },
    { text: "Swazi Lilangeni", value: "SZL" },
    { text: "Thai Baht", value: "THB" },
    { text: "Tajikistani Somoni", value: "TJS" },
    { text: "Turkmenistani Manat", value: "TMT" },
    { text: "Tunisian Dinar", value: "TND" },
    { text: `Tongan Pa"anga`, value: "TOP" },
    { text: "Turkish Lira", value: "TRY" },
    { text: "Trinidadian Dollar", value: "TTD" },
    { text: "Tuvaluan Dollar", value: "TVD" },
    { text: "Taiwan New Dollar", value: "TWD" },
    { text: "Tanzanian Shilling", value: "TZS" },
    { text: "Ukrainian Hryvnia", value: "UAH" },
    { text: "Ugandan Shilling", value: "UGX" },
    { text: "US Dollar", value: "USD" },
    { text: "Uruguayan Peso", value: "UYU" },
    { text: "Uzbekistani Som", value: "UZS" },
    { text: "Venezuelan Bolívar", value: "VEF" },
    { text: "Venezuelan Bolívar", value: "VES" },
    { text: "Vietnamese Dong", value: "VND" },
    { text: "Vanuatu Vatu", value: "VUV" },
    { text: "Samoan Tala", value: "WST" },
    { text: "Central African CFA Franc BEAC", value: "XAF" },
    { text: "Bitcoin", value: "XBT" },
    { text: "East Caribbean Dollar", value: "XCD" },
    { text: "CFA Franc", value: "XOF" },
    { text: "CFP Franc", value: "XPF" },
    { text: "Yemeni Rial", value: "YER" },
    { text: "South African Rand", value: "ZAR" },
    { text: "Zambian Kwacha", value: "ZMW" },
    { text: "Zimbabwean Dollar", value: "ZWD" }
  ]);
  return { currency };
}
